name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Github Repository에 올린 파일들을 불러오기
        uses: actions/checkout@v4

      - name: JDK 17버전 설치
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: gradlew에 실행 권한 부여
        run: chmod +x ./gradlew

      - name: 테스트 및 빌드하기
        run: ./gradlew clean build



      - name: 빌드된 파일 이름 변경하기
        run: mv ./build/libs/movietalk-0.0.1-SNAPSHOT.jar ./project.jar


      - name: SCP로 EC2에 빌드된 파일 전송하기
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_KEY }}
          source: project.jar
          target: /home/ubuntu/

      - name: SSH로 EC2에 접속하여 애플리케이션 실행하기
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_KEY }}
          script_stop: true
          script: |
            # 기존 8080 포트에서 실행 중인 프로세스 종료
            sudo fuser -k -n tcp 8080 || true

            # 기존 로그 파일 삭제 또는 백업 (선택 사항)
            rm -f /home/ubuntu/output.log

            # 새로 전송된 jar 실행
            nohup java -jar /home/ubuntu/project.jar > /home/ubuntu/output.log 2>&1 &